import { BusRoute, Guide, Station, StationMap } from './types';

export const stations: Station[] = [
  {
    id: 'mo-chit',
    name: { th: 'หมอชิต 2', my: 'မော်ချစ် ၂', en: 'Mo Chit 2' },
    fullName: {
      th: 'สถานีขนส่งผู้โดยสารกรุงเทพ (จตุจักร)',
      my: 'ဘန်ကောက် ခရီးသည်ပို့ဆောင်ရေးဂိတ် (ချာတူချက်)',
      en: 'Bangkok Bus Terminal (Chatuchak)',
    },
    region: { th: 'สายเหนือและอีสาน', my: 'မြောက်ပိုင်းနှင့် အရှေ့မြောက်ပိုင်း', en: 'North & Northeast' },
    address: {
      th: 'ถนนกำแพงเพชร 2 แขวงจตุจักร เขตจตุจักร กรุงเทพฯ 10900',
      my: 'ကမ်ဖန်ဖက် ၂ လမ်း၊ ချာတူချက်၊ ဘန်ကောက် ၁၀၉၀၀',
      en: 'Kamphaeng Phet 2 Rd, Chatuchak, Bangkok 10900',
    },
    hours: '04:00 – 23:30',
    phone: '02-936-2852',
    lat: 13.8126,
    lng: 100.5478,
    color: '#C4491D',
    accent: '#F4C7A8',
    icon: 'bus',
    transit: [
      {
        icon: 'train',
        label: { th: 'BTS หมอชิต + MRT สวนจตุจักร', my: 'BTS မော်ချစ် + MRT ချာတူချက်ဥယျာဉ်', en: 'BTS Mo Chit + MRT Chatuchak' },
        detail: {
          th: 'ลง BTS หมอชิต ทางออก 3 แล้วต่อวินมอไซค์หรือเดิน 10–15 นาที / ลง MRT สวนจตุจักร ทางออก 2',
          my: 'BTS မော်ချစ် ထွက်ပေါက် ၃ မှ ဆိုင်ကယ်ဆိုင်ကယ် သို့မဟုတ် ၁၀–၁၅ မိနစ် လမ်းလျှောက် / MRT ထွက်ပေါက် ၂',
          en: 'BTS Mo Chit exit 3 then motorbike taxi or 10–15 min walk / MRT Chatuchak Park exit 2',
        },
      },
      {
        icon: 'car',
        label: { th: 'แท็กซี่ / Grab', my: 'တက္ကစီ / Grab', en: 'Taxi / Grab' },
        detail: {
          th: 'บอกคนขับ “หมอชิตใหม่” หรือ “บขส. หมอชิต 2” ไม่ใช่หมอชิตเก่า',
          my: 'ယာဉ်မောင်းအား “မော်ချစ်အသစ်” သို့မဟုတ် “ဘတ်စ်ဂိတ် မော်ချစ် ၂” ဟု ပြောပါ။ အဟောင်းမဟုတ်ပါ။',
          en: 'Say “Mo Chit Mai” or “Mo Chit 2 terminal” — not the old Mo Chit stop.',
        },
      },
      {
        icon: 'airplane',
        label: { th: 'จากดอนเมือง (DMK)', my: 'ဒွန်မောင်းလေဆိပ်မှ', en: 'From Don Mueang (DMK)' },
        detail: {
          th: 'A1/A3 หรือแท็กซี่ 25–40 นาที ขึ้นกับรถติด ราคาประมาณ 150–250 บาท',
          my: 'A1/A3 သို့မဟုတ် တက္ကစီ ၂၅–၄၀ မိနစ်။ ခန့်မှန်း ၁၅၀–၂၅၀ ဘတ်',
          en: 'A1/A3 airport bus or taxi 25–40 min, about 150–250 THB.',
        },
      },
    ],
    facilities: [
      { icon: 'ticket', label: { th: 'เคาน์เตอร์ตั๋ว 24 บริษัท', my: 'လက်မှတ်ကောင်တာ ၂၄ ခု', en: '24 company counters' } },
      { icon: 'fast-food', label: { th: 'ศูนย์อาหารชั้น 2', my: 'ဒုတိယထပ် စားသောက်ဆိုင်', en: '2F food court' } },
      { icon: 'cash', label: { th: 'ตู้เอทีเอ็ม / แลกเงิน', my: 'ATM / ငွေလဲ', en: 'ATM / exchange' } },
      { icon: 'medkit', label: { th: 'ห้องพยาบาล', my: 'ဆေးခန်း', en: 'First aid' } },
      { icon: 'wifi', label: { th: 'Wi-Fi ฟรี', my: 'အခမဲ့ Wi-Fi', en: 'Free Wi-Fi' } },
      { icon: 'lock-closed', label: { th: 'ล็อกเกอร์เก็บของ', my: 'ပစ္စည်းသိမ်းလော့ကာ', en: 'Lockers' } },
      { icon: 'pricetag', label: { th: 'ร้านสะดวกซื้อ 7-Eleven', my: '7-Eleven', en: '7-Eleven' } },
      { icon: 'people', label: { th: 'ห้องละหมาด / มุสลิม', my: 'ဆွလာတ်ခန်း', en: 'Prayer room' } },
    ],
    zones: [
      { id: 'a', name: { th: 'โซน A ชานชาลา 1–12', my: 'ဇုန် A ပလက်ဖောင်း ၁–၁၂', en: 'Zone A platforms 1–12' }, note: { th: 'อีสาน — ขอนแก่น อุดร หนองคาย อุบล', my: 'အီစန် — ခွန်ကဲန်၊ အူဒွန်၊ နောင်ခိုင်း၊ အူဘွန်', en: 'Isaan — Khon Kaen, Udon, Nong Khai, Ubon' } },
      { id: 'b', name: { th: 'โซน B ชานชาลา 13–22', my: 'ဇုန် B ပလက်ဖောင်း ၁၃–၂၂', en: 'Zone B platforms 13–22' }, note: { th: 'เหนือ — เชียงใหม่ เชียงราย พิษณุโลก แม่สอด', my: 'မြောက် — ချင်းမိုင်၊ ချင်းရိုင်း၊ ဖစ်စနုလော့၊ မဲဆောက်', en: 'North — Chiang Mai, Chiang Rai, Phitsanulok, Mae Sot' } },
      { id: 'c', name: { th: 'โซน C ตั๋วและห้องรอ', my: 'ဇုန် C လက်မှတ်နှင့် စောင့်ခန်း', en: 'Zone C tickets & waiting' }, note: { th: 'เคาน์เตอร์ตั๋วทั้งหมดอยู่ชั้น 1 ฝั่งกำแพงเพชร', my: 'လက်မှတ်ကောင်တာအားလုံး ပထမထပ်၊ ကမ်ဖန်ဖက်ဘက်', en: 'All ticket counters on 1F facing Kamphaeng Phet' } },
    ],
    roads: [
      { name: { th: 'ถ.กำแพงเพชร 2', my: 'ကမ်ဖန်ဖက် ၂ လမ်း', en: 'Kamphaeng Phet 2 Rd' }, how: { th: 'ทางเข้าหลักด้านหน้าสถานี แท็กซี่จอดฝั่งนี้', my: 'ဂိတ်ရှေ့ အဓိကဝင်ပေါက်။ တက္ကစီများ ဤဘက်တွင်ရပ်သည်', en: 'Main front entrance. Taxis wait on this side.' } },
      { name: { th: 'ถ.พหลโยธิน', my: 'ဖဟိုယိုသင်လမ်း', en: 'Phahonyothin Rd' }, how: { th: 'เลี้ยวเข้ากำแพงเพชร 2 จากแยกเกษตร / จตุจักร', my: 'ကဆက် / ချာတူချက်လမ်းဆုံမှ ကမ်ဖန်ဖက် ၂ သို့ကွေ့ပါ', en: 'Turn into Kamphaeng Phet 2 from Kaset or Chatuchak junction.' } },
      { name: { th: 'ทางด่วนงามวงศ์วาน', my: 'ငမ်ဝေါင်ဝမ် အမြန်လမ်း', en: 'Ngarm Wongwan expressway' }, how: { th: 'ลงปากทางจตุจักร แล้วตามป้าย บขส. หมอชิต', my: 'ချာတူချက်ထွက်ပေါက်မှဆင်းပြီး မော်ချစ်ဘတ်စ်ဂိတ် ဆိုင်းဘုတ်လိုက်ပါ', en: 'Exit Chatuchak then follow Mo Chit terminal signs.' } },
    ],
    tips: [
      { th: 'คนพม่าจำนวนมากใช้หมอชิตไปแม่สอด (ด่านพรมแดนเมียวดี) — ซื้อตั๋วล่วงหน้าช่วงเช้า', my: 'မြန်မာများ မဲဆောက် (မြဝတီနယ်စပ်) သို့သွားရန် မော်ချစ်ကို အသုံးများသည် — နံနက်ပိုင်းတွင် ကြိုတင်ဝယ်ပါ', en: 'Many Myanmar travellers use Mo Chit for Mae Sot (Myawaddy border) — buy tickets in the morning.' },
      { th: 'อย่าสับสนกับหมอชิตเก่า (BTS) — สถานีขนส่งอยู่ลึกเข้าไปในกำแพงเพชร 2', my: 'မော်ချစ်အဟောင်း (BTS) နှင့် မရောပါနှင့် — ဘတ်စ်ဂိတ်သည် ကမ်ဖန်ဖက် ၂ အတွင်းပိုင်းတွင်ရှိသည်', en: 'Don’t confuse with old Mo Chit BTS — the terminal is further along Kamphaeng Phet 2.' },
      { th: 'ขึ้นรถก่อนเวลา 15–20 นาที ชานชาลายาวและประกาศเป็นภาษาไทย', my: '၁၅–၂၀ မိနစ် ကြိုတင်တက်ပါ။ ပလက်ဖောင်းရှည်ပြီး ကြေညာချက်များ ထိုင်းလိုဖြစ်သည်', en: 'Board 15–20 min early. Platforms are long and announcements are in Thai.' },
    ],
    updated: '2026-03-12',
  },
  {
    id: 'sai-tai',
    name: { th: 'สายใต้ใหม่', my: 'ဆိုင်တိုင်းအသစ်', en: 'Sai Tai Mai' },
    fullName: {
      th: 'สถานีขนส่งผู้โดยสารกรุงเทพ (ถนนบรมราชชนนี)',
      my: 'ဘန်ကောက် ခရီးသည်ပို့ဆောင်ရေးဂိတ် (ဘိုရမ်ရာ့ချာနီလမ်း)',
      en: 'Bangkok Bus Terminal (Borommaratchachonnani)',
    },
    region: { th: 'สายใต้และตะวันตก', my: 'တောင်ပိုင်းနှင့် အနောက်ပိုင်း', en: 'South & West' },
    address: {
      th: 'ถนนบรมราชชนนี แขวงฉิมพลี เขตตลิ่งชัน กรุงเทพฯ 10170',
      my: 'ဘိုရမ်ရာ့ချာနီလမ်း၊ ချင်ဖလီ၊ တလင်ချန်၊ ဘန်ကောက် ၁၀၁၇၀',
      en: 'Borommaratchachonnani Rd, Chimphli, Taling Chan, Bangkok 10170',
    },
    hours: '04:00 – 23:00',
    phone: '02-894-6122',
    lat: 13.7829,
    lng: 100.4372,
    color: '#1B5E56',
    accent: '#BFE3DC',
    icon: 'boat',
    transit: [
      {
        icon: 'bus',
        label: { th: 'รถเมล์ / รถตู้จากสนามหลวง', my: 'မြို့တွင်းဘတ်စ် / ဗန် (စနမ်လွမ်မှ)', en: 'City bus / van from Sanam Luang' },
        detail: {
          th: 'สาย 511, 515 หรือรถตู้ “สายใต้ใหม่” จากอนุสาวรีย์ประชาธิปไตย / สนามหลวง 45–70 นาที',
          my: 'လမ်းကြောင်း ၅၁၁၊ ၅၁၅ သို့မဟုတ် ဒီမိုကရေစီအထိမ်းအမှတ် / စနမ်လွမ်မှ ဗန် ၄၅–၇၀ မိနစ်',
          en: 'Bus 511, 515 or “Sai Tai Mai” van from Democracy Monument / Sanam Luang, 45–70 min.',
        },
      },
      {
        icon: 'train',
        label: { th: 'BTS บางหว้า + ต่อรถ', my: 'BTS ဘန်ဝါ + ဆက်စီး', en: 'BTS Bang Wa + transfer' },
        detail: {
          th: 'ลงบางหว้า แล้วต่อวินหรือแท็กซี่อีก 15–20 นาที',
          my: 'ဘန်ဝါမှဆင်းပြီး ဆိုင်ကယ် သို့မဟုတ် တက္ကစီ နောက်ထပ် ၁၅–၂၀ မိနစ်',
          en: 'Alight Bang Wa then motorbike/taxi another 15–20 min.',
        },
      },
      {
        icon: 'airplane',
        label: { th: 'จากสุวรรณภูมิ (BKK)', my: 'သုဝဏ္ဏဘူမိလေဆိပ်မှ', en: 'From Suvarnabhumi (BKK)' },
        detail: {
          th: 'Airport Rail Link เข้าเมือง แล้วต่อแท็กซี่/Grab ไปตลิ่งชัน รวม 90–130 นาที',
          my: 'Airport Rail Link ဖြင့်မြို့တွင်းဝင်ပြီး တလင်ချန်သို့ တက္ကစီ/Grab။ စုစုပေါင်း ၉၀–၁၃၀ မိနစ်',
          en: 'Airport Rail Link into town then taxi/Grab to Taling Chan. Total 90–130 min.',
        },
      },
    ],
    facilities: [
      { icon: 'ticket', label: { th: 'ตั๋วชั้นล่างฝั่งใต้', my: 'အောက်ထပ် တောင်ဘက် လက်မှတ်', en: 'Tickets on south 1F' } },
      { icon: 'fast-food', label: { th: 'ร้านอาหารทะเลสายใต้', my: 'တောင်ပိုင်းပင်လယ်စာ', en: 'Southern seafood stalls' } },
      { icon: 'bed', label: { th: 'ที่พักค้างคืนใกล้สถานี', my: 'ဂိတ်အနီးညအိပ်ရိပ်သာ', en: 'Nearby overnight inns' } },
      { icon: 'cash', label: { th: 'ตู้เอทีเอ็ม', my: 'ATM', en: 'ATMs' } },
      { icon: 'wifi', label: { th: 'Wi-Fi ฟรี', my: 'အခမဲ့ Wi-Fi', en: 'Free Wi-Fi' } },
      { icon: 'bag-handle', label: { th: 'ห้องฝากกระเป๋า', my: 'အိတ်အပ်ခန်း', en: 'Left luggage' } },
    ],
    zones: [
      { id: 's1', name: { th: 'ชานชาลา 1–8 ภาคใต้ตอนบน', my: 'ပလက်ဖောင်း ၁–၈ အထက်တောင်ပိုင်း', en: 'Platforms 1–8 Upper South' }, note: { th: 'หัวหิน ประจวบ ชุมพร สุราษฎร์', my: 'ဟွာဟင်၊ ပရာကျွတ်၊ ချွန်ဖွန်၊ စူရတ်', en: 'Hua Hin, Prachuap, Chumphon, Surat' } },
      { id: 's2', name: { th: 'ชานชาลา 9–16 ภาคใต้ตอนล่าง', my: 'ပလက်ဖောင်း ၉–၁၆ အောက်တောင်ပိုင်း', en: 'Platforms 9–16 Deep South' }, note: { th: 'ภูเก็ต กระบี่ หาดใหญ่ นครศรี', my: 'ဖူးခက်၊ ခရာဘီ၊ ဟတ်ယိုင်၊ နခွန်စီ', en: 'Phuket, Krabi, Hat Yai, Nakhon Si' } },
      { id: 's3', name: { th: 'ชานชาลา 17–20 ตะวันตก', my: 'ပလက်ဖောင်း ၁၇–၂၀ အနောက်', en: 'Platforms 17–20 West' }, note: { th: 'กาญจนบุรี ราชบุรี ระนอง (Kawthaung)', my: 'ကန်ချနဘူရီ၊ ရတ်ချဘူရီ၊ ရနောင်း (ကော့သောင်း)', en: 'Kanchanaburi, Ratchaburi, Ranong (Kawthaung)' } },
    ],
    roads: [
      { name: { th: 'ถ.บรมราชชนนี', my: 'ဘိုရမ်ရာ့ချာနီလမ်း', en: 'Borommaratchachonnani Rd' }, how: { th: 'ทางเข้าหลัก รถทุกชนิดเข้าได้ ระวังรถติดช่วงเย็น', my: 'အဓိကဝင်ပေါက်။ ညနေပိုင်း ယာဉ်ကြောပိတ်တတ်သည်', en: 'Main access. Expect evening congestion.' } },
      { name: { th: 'ถ.ราชพฤกษ์', my: 'ရာ့ချာဖရึกလမ်း', en: 'Ratchaphruek Rd' }, how: { th: 'เลี้ยวซ้ายเข้าบรมราชชนนีจากแยกพุทธมณฑลสาย 2', my: 'ဖုတ္ဓမဏ္ဍိုင် ၂ လမ်းဆုံမှ ဘိုရမ်ရာ့ချာနီသို့ ဘယ်ကွေ့ပါ', en: 'Turn left onto Borommaratchachonnani from Phutthamonthon Sai 2.' } },
    ],
    tips: [
      { th: 'คนพม่าที่ไปเกาะท่อง / Kawthaung ใช้สายใต้ใหม่ไประนอง แล้วต่อเรือ', my: 'ကော့သောင်းသို့သွားသူများ ဆိုင်တိုင်းအသစ်မှ ရနောင်းသို့သွားပြီး လှေဆက်စီးကြသည်', en: 'Travellers to Kawthaung take Sai Tai Mai to Ranong then a boat.' },
      { th: 'รถกลางคืนไปภูเก็ต/หาดใหญ่ ออก 18:00–20:30 ซื้อก่อน 16:00', my: 'ဖူးခက်/ဟတ်ယိုင် ညကား ၁၈:၀၀–၂၀:၃၀ ထွက်သည်။ ၁၆:၀၀ မတိုင်မီဝယ်ပါ', en: 'Night buses to Phuket/Hat Yai leave 18:00–20:30. Buy before 16:00.' },
      { th: 'สถานีอยู่ชานเมือง เผื่อเวลาเดินทางจากสุขุมวิทอย่างน้อย 90 นาที', my: 'ဂိတ်သည် ဆင်ခြေဖုံးတွင်ရှိသည်။ သုခွမ်ဝစ်မှ အနည်းဆုံး ၉၀ မိနစ် ကြိုတင်ပါ', en: 'The terminal is suburban — allow 90+ min from Sukhumvit.' },
    ],
    updated: '2026-03-10',
  },
  {
    id: 'ekkamai',
    name: { th: 'เอกมัย', my: 'အက်ကမိုင်', en: 'Ekkamai' },
    fullName: {
      th: 'สถานีขนส่งผู้โดยสารกรุงเทพ (เอกมัย)',
      my: 'ဘန်ကောက် ခရီးသည်ပို့ဆောင်ရေးဂိတ် (အက်ကမိုင်)',
      en: 'Bangkok Bus Terminal (Ekkamai)',
    },
    region: { th: 'สายตะวันออก', my: 'အရှေ့ပိုင်း', en: 'East coast' },
    address: {
      th: 'ซอยสุขุมวิท 40 / ถ.สุขุมวิท แขวงพระโขนง เขตคลองเตย กรุงเทพฯ 10110',
      my: 'ဆွိုင် သုခွမ်ဝစ် ၄၀ / သုခွမ်ဝစ်လမ်း၊ ဖရာခနောင်၊ ခလောင်တို၊ ဘန်ကောက် ၁၀၁၁၀',
      en: 'Soi Sukhumvit 40 / Sukhumvit Rd, Phra Khanong, Khlong Toei, Bangkok 10110',
    },
    hours: '05:00 – 23:00',
    phone: '02-391-8097',
    lat: 13.7195,
    lng: 100.5851,
    color: '#2B4C7E',
    accent: '#C9D7EE',
    icon: 'sunny',
    transit: [
      {
        icon: 'train',
        label: { th: 'BTS เอกมัย', my: 'BTS အက်ကမိုင်', en: 'BTS Ekkamai' },
        detail: {
          th: 'ลงสถานีเอกมัย ทางออก 2 ข้ามสะพานลอยมาที่สถานีขนส่งทันที (2 นาที)',
          my: 'အက်ကမိုင်ဘူတာ ထွက်ပေါက် ၂ မှ လူကူးတံတားဖြတ်လျှင် ဘတ်စ်ဂိတ်သို့ ချက်ချင်းရောက်သည် (၂ မိနစ်)',
          en: 'BTS Ekkamai exit 2 — cross the skywalk, 2 minutes to the terminal.',
        },
      },
      {
        icon: 'airplane',
        label: { th: 'จากสุวรรณภูมิ', my: 'သုဝဏ္ဏဘူမိမှ', en: 'From Suvarnabhumi' },
        detail: {
          th: 'Airport Rail Link ถึงพระโขนง แล้วต่อ BTS 1 สถานี หรือแท็กซี่ 35–50 นาที',
          my: 'Airport Rail Link ဖြင့် ဖရာခနောင်သို့၊ ထို့နောက် BTS တစ်ဘူတာ သို့မဟုတ် တက္ကစီ ၃၅–၅၀ မိနစ်',
          en: 'Airport Rail Link to Phra Khanong then 1 BTS stop, or taxi 35–50 min.',
        },
      },
    ],
    facilities: [
      { icon: 'ticket', label: { th: 'ตั๋วชั้นล่าง', my: 'အောက်ထပ်လက်မှတ်', en: 'Ground-floor tickets' } },
      { icon: 'cafe', label: { th: 'คาเฟ่และร้านสะดวกซื้อ', my: 'ကော်ဖီဆိုင်နှင့် ဆိုင်ငယ်', en: 'Cafes & convenience' } },
      { icon: 'car', label: { th: 'จุดจอดแท็กซี่หน้าสถานี', my: 'ဂိတ်ရှေ့ တက္ကစီရပ်နား', en: 'Taxi rank out front' } },
      { icon: 'wifi', label: { th: 'Wi-Fi', my: 'Wi-Fi', en: 'Wi-Fi' } },
    ],
    zones: [
      { id: 'e1', name: { th: 'ชานชาลาพัทยา–ระยอง', my: 'ပတ္တားယား–ရယောင်း ပလက်ဖောင်း', en: 'Pattaya–Rayong platforms' }, note: { th: 'พัทยา นาจอมเทียน ระยอง บ้านเพ', my: 'ပတ္တားယား၊ နာဂျွမ်သီယန်၊ ရယောင်း၊ ဘန်ဖေး', en: 'Pattaya, Na Jomtien, Rayong, Ban Phe' } },
      { id: 'e2', name: { th: 'ชานชาลาจันทบุรี–ตราด', my: 'ချန်သဘူရီ–ထရာ့ဒ် ပလက်ဖောင်း', en: 'Chanthaburi–Trat platforms' }, note: { th: 'ต่อเรือเกาะช้าง / เกาะกูด ที่ตราดหรือแหลมงอบ', my: 'ထရာ့ဒ် သို့မဟုတ် လမ်ငော့မှ ကိုးချန် / ကိုးကုဒ် လှေဆက်စီး', en: 'Connect to Koh Chang / Koh Kood boats at Trat or Laem Ngop' } },
    ],
    roads: [
      { name: { th: 'ถ.สุขุมวิท', my: 'သုခွမ်ဝစ်လမ်း', en: 'Sukhumvit Rd' }, how: { th: 'สถานีอยู่ซอยสุขุมวิท 40 ฝั่งขาออกเมือง', my: 'ဂိတ်သည် သုခွမ်ဝစ် ဆွိုင် ၄၀၊ မြို့အထွက်ဘက်တွင်ရှိသည်', en: 'The terminal sits on Soi Sukhumvit 40, outbound side.' } },
      { name: { th: 'ทางด่วนศรีรัช', my: 'စီရတ် အမြန်လမ်း', en: 'Si Rat expressway' }, how: { th: 'ลงสุขุมวิท แล้วเลี้ยวเข้าซอย 40', my: 'သုခွမ်ဝစ်မှဆင်းပြီး ဆွိုင် ၄၀ သို့ကွေ့ပါ', en: 'Exit Sukhumvit then turn into Soi 40.' } },
    ],
    tips: [
      { th: 'สถานีเล็กที่สุดในสามแห่ง — หาตั๋วง่าย แต่ที่นั่งน้อยช่วงศุกร์เย็น', my: 'ဂိတ်သုံးခုအနက် အငယ်ဆုံး — လက်မှတ်ရလွယ်သော်လည်း သောကြာညနေတွင် ခုံနည်းသည်', en: 'Smallest of the three — easy to find tickets, but Friday evenings sell out.' },
      { th: 'รถตู้พัทยาออกบ่อยมาก ทุก 30 นาที แต่กระเป๋าใหญ่ขึ้นไม่ได้บางคัน', my: 'ပတ္တားယားဗန်များ ၃၀ မိနစ်တစ်ကြိမ် ထွက်သည်။ အိတ်ကြီးများ အချို့ကားတွင် မတင်နိုင်', en: 'Pattaya vans leave every 30 min. Large luggage may not fit some vans.' },
    ],
    updated: '2026-03-08',
  },
];

export const routes: BusRoute[] = [
  {
    id: 'mc-cmai-vip',
    stationId: 'mo-chit',
    destination: { th: 'เชียงใหม่', my: 'ချင်းမိုင်', en: 'Chiang Mai' },
    province: { th: 'เชียงใหม่', my: 'ချင်းမိုင်', en: 'Chiang Mai' },
    company: { th: 'นครชัยแอร์', my: 'နခွန်ချိုင်အဲယား', en: 'Nakhonchai Air' },
    type: 'vip',
    durationMin: 600,
    priceMin: 720,
    priceMax: 890,
    times: ['08:00', '09:30', '14:00', '19:00', '20:00', '21:00'],
    platform: 'B-16',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'ตาก นครสวรรค์ ลำปาง', my: 'တာ့ခ်၊ နခွန်စဝမ်၊ လမ်ပန်', en: 'Tak, Nakhon Sawan, Lampang' },
    notes: { th: 'ที่นอนปรับเอน มีผ้าห่ม อาหารกล่อง 1 มื้อ ห้ามสูบ', my: 'လှဲအိပ်ခုံ၊ စောင်၊ ထမင်းဘူး ၁ နပ်။ ဆေးလိပ်မသောက်ရ', en: 'Recliner, blanket, 1 meal box. No smoking.' },
  },
  {
    id: 'mc-cmai-1',
    stationId: 'mo-chit',
    destination: { th: 'เชียงใหม่', my: 'ချင်းမိုင်', en: 'Chiang Mai' },
    province: { th: 'เชียงใหม่', my: 'ချင်းမိုင်', en: 'Chiang Mai' },
    company: { th: 'บขส. / สมบัติทัวร์', my: 'ဘတ်စ်ကုမ္ပဏီ / ဆွမ်ဘတ်', en: 'The Transport Co. / Sombat' },
    type: 'first',
    durationMin: 630,
    priceMin: 580,
    priceMax: 680,
    times: ['07:00', '10:00', '17:30', '19:30', '21:30'],
    platform: 'B-14',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'นครสวรรค์ ตาก', my: 'နခွန်စဝမ်၊ တာ့ခ်', en: 'Nakhon Sawan, Tak' },
    notes: { th: 'แอร์ 2+2 มีจุดจอดพัก 2 ครั้ง', my: 'အဲယား ၂+၂၊ နားနေရန် ၂ ကြိမ်ရပ်', en: '2+2 A/C, two rest stops.' },
  },
  {
    id: 'mc-cri',
    stationId: 'mo-chit',
    destination: { th: 'เชียงราย', my: 'ချင်းရိုင်း', en: 'Chiang Rai' },
    province: { th: 'เชียงราย', my: 'ချင်းရိုင်း', en: 'Chiang Rai' },
    company: { th: 'กรุงเทพธุรกิจทัวร์', my: 'ဘန်ကောက် ခရီးသွား', en: 'Bangkok Buslines' },
    type: 'vip',
    durationMin: 660,
    priceMin: 750,
    priceMax: 880,
    times: ['08:30', '19:00', '20:15'],
    platform: 'B-18',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'แพร่ พะเยา', my: 'ဖရဲ၊ ဖယောင်း', en: 'Phrae, Phayao' },
    notes: { th: 'ต่อรถตู้แม่สายได้ที่เชียงราย', my: 'ချင်းရိုင်းမှ မဲဆိုင်ဗန် ဆက်စီးနိုင်', en: 'Mae Sai vans connect in Chiang Rai.' },
  },
  {
    id: 'mc-maesot',
    stationId: 'mo-chit',
    destination: { th: 'แม่สอด', my: 'မဲဆောက်', en: 'Mae Sot' },
    province: { th: 'ตาก', my: 'တာ့ခ်', en: 'Tak' },
    company: { th: 'ชนะชัยชนะทัวร์ / สมบัติ', my: 'ချနာချိုင်ချနာ / ဆွမ်ဘတ်', en: 'Chanachai / Sombat' },
    type: 'first',
    durationMin: 480,
    priceMin: 420,
    priceMax: 560,
    times: ['07:30', '09:00', '11:00', '20:00', '21:00'],
    platform: 'B-20',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'นครสวรรค์ ตาก แม่สอด', my: 'နခွန်စဝမ်၊ တာ့ခ်၊ မဲဆောက်', en: 'Nakhon Sawan, Tak, Mae Sot' },
    notes: {
      th: 'จุดสำคัญสำหรับผู้โดยสารเมียนมา — จากแม่สอดต่อวิน/สองแถวไปด่านพรมแดนไทย–เมียวดี 15–25 นาที ด่านเปิด 05:30–20:00',
      my: 'မြန်မာခရီးသည်များအတွက် အရေးကြီးသည် — မဲဆောက်မှ မြဝတီနယ်စပ်သို့ ဆိုင်ကယ်/ဆွန် grav ၁၅–၂၅ မိနစ်။ ဂိတ်ဖွင့် ၀၅:၃၀–၂၀:၀၀',
      en: 'Key for Myanmar travellers. From Mae Sot, songthaew/motorbike 15–25 min to Thai–Myawaddy gate. Gate 05:30–20:00.',
    },
  },
  {
    id: 'mc-kk',
    stationId: 'mo-chit',
    destination: { th: 'ขอนแก่น', my: 'ခွန်ကဲန်', en: 'Khon Kaen' },
    province: { th: 'ขอนแก่น', my: 'ခွန်ကဲန်', en: 'Khon Kaen' },
    company: { th: 'นครชัยแอร์', my: 'နခွန်ချိုင်အဲယား', en: 'Nakhonchai Air' },
    type: 'vip',
    durationMin: 390,
    priceMin: 450,
    priceMax: 560,
    times: ['08:00', '10:30', '13:00', '16:00', '20:30', '22:00'],
    platform: 'A-6',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'สระบุรี นครราชสีมา', my: 'စရာဘူရီ၊ နခွန်ရာ့ချစီမာ', en: 'Saraburi, Nakhon Ratchasima' },
    notes: { th: 'ที่นั่งกว้าง อาหารว่าง', my: 'ခုံကျယ်၊ အဆာပြေ', en: 'Wide seats, snacks.' },
  },
  {
    id: 'mc-udon',
    stationId: 'mo-chit',
    destination: { th: 'อุดรธานี', my: 'အူဒွန်ဌာနီ', en: 'Udon Thani' },
    province: { th: 'อุดรธานี', my: 'အူဒွန်ဌာနီ', en: 'Udon Thani' },
    company: { th: 'เชิดชัยทัวร์', my: 'ချာ့ချိုင်', en: 'Cherdchai' },
    type: 'first',
    durationMin: 480,
    priceMin: 480,
    priceMax: 620,
    times: ['08:15', '12:00', '19:45', '21:15'],
    platform: 'A-8',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'ขอนแก่น', my: 'ခွန်ကဲန်', en: 'Khon Kaen' },
    notes: { th: 'ต่อหนองคาย / ท่านาแล้ง (ลาว) ได้', my: 'နောင်ခိုင်း / သာနာလောင်း (လာအို) ဆက်စီးနိုင်', en: 'Connect to Nong Khai / Thanaleng (Laos).' },
  },
  {
    id: 'mc-nkhai',
    stationId: 'mo-chit',
    destination: { th: 'หนองคาย', my: 'နောင်ခိုင်း', en: 'Nong Khai' },
    province: { th: 'หนองคาย', my: 'နောင်ခိုင်း', en: 'Nong Khai' },
    company: { th: 'บขส.', my: 'ဘတ်စ်ကုမ္ပဏီ', en: 'The Transport Co.' },
    type: 'first',
    durationMin: 540,
    priceMin: 520,
    priceMax: 650,
    times: ['20:00', '20:45'],
    platform: 'A-10',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'ขอนแก่น อุดร', my: 'ခွန်ကဲန်၊ အူဒွန်', en: 'Khon Kaen, Udon' },
    notes: { th: 'สะพานมิตรภาพไปเวียงจันทน์ เปิด 06:00–22:00', my: 'ဗီယင်ကျန်းသို့ ချစ်ကြည်ရေးတံတား ဖွင့် ၀၆:၀၀–၂၂:၀၀', en: 'Friendship Bridge to Vientiane open 06:00–22:00.' },
  },
  {
    id: 'mc-ubon',
    stationId: 'mo-chit',
    destination: { th: 'อุบลราชธานี', my: 'အူဘွန်ရာ့ချဌာနီ', en: 'Ubon Ratchathani' },
    province: { th: 'อุบลราชธานี', my: 'အူဘွန်ရာ့ချဌာနီ', en: 'Ubon Ratchathani' },
    company: { th: 'นครชัยแอร์', my: 'နခွန်ချိုင်အဲယား', en: 'Nakhonchai Air' },
    type: 'vip',
    durationMin: 540,
    priceMin: 590,
    priceMax: 720,
    times: ['08:00', '19:30', '20:30'],
    platform: 'A-4',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'นครราชสีมา บุรีรัมย์ สุรินทร์', my: 'နခွန်ရာ့ချစီမာ၊ ဘူရီရမ်၊ စူရင်', en: 'Korat, Buriram, Surin' },
    notes: { th: 'ใกล้ชายแดนปากเซ (ลาวใต้)', my: 'ပါ့ခ်ဆေး (တောင်လာအို) နယ်စပ်အနီး', en: 'Near Pakse (southern Laos) border.' },
  },
  {
    id: 'mc-korat',
    stationId: 'mo-chit',
    destination: { th: 'นครราชสีมา', my: 'နခွန်ရာ့ချစီမာ (ကိုရတ်)', en: 'Nakhon Ratchasima' },
    province: { th: 'นครราชสีมา', my: 'နခွန်ရာ့ချစီမာ', en: 'Nakhon Ratchasima' },
    company: { th: 'บขส.', my: 'ဘတ်စ်ကုမ္ပဏီ', en: 'The Transport Co.' },
    type: 'express',
    durationMin: 210,
    priceMin: 220,
    priceMax: 280,
    times: ['06:30', '08:00', '10:00', '12:00', '14:00', '16:00', '18:00', '20:00'],
    platform: 'A-2',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'สระบุรี', my: 'စရာဘူရီ', en: 'Saraburi' },
    notes: { th: 'รถบ่อย ที่นั่งชั้น 2 ราคาถูก', my: 'မကြာခဏထွက်၊ ဒုတိယတန်းဈေးချို', en: 'Frequent, cheap 2nd-class seats.' },
  },
  {
    id: 'mc-phits',
    stationId: 'mo-chit',
    destination: { th: 'พิษณุโลก', my: 'ဖစ်စနုလော့', en: 'Phitsanulok' },
    province: { th: 'พิษณုโลก', my: 'ဖစ်စနုလော့', en: 'Phitsanulok' },
    company: { th: 'สมบัติทัวร์', my: 'ဆွမ်ဘတ်', en: 'Sombat Tour' },
    type: 'first',
    durationMin: 300,
    priceMin: 320,
    priceMax: 410,
    times: ['07:45', '11:00', '15:30', '19:00'],
    platform: 'B-13',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'นครสวรรค์', my: 'နခွန်စဝမ်', en: 'Nakhon Sawan' },
    notes: { th: 'ต่อสุโขทัยได้', my: 'စုခိုထိုင်း ဆက်စီးနိုင်', en: 'Sukhothai connections available.' },
  },
  {
    id: 'mc-lampang',
    stationId: 'mo-chit',
    destination: { th: 'ลำปาง', my: 'လမ်ပန်', en: 'Lampang' },
    province: { th: 'ลำปาง', my: 'လမ်ပန်', en: 'Lampang' },
    company: { th: 'นครชัยแอร์', my: 'နခွန်ချိုင်အဲယား', en: 'Nakhonchai Air' },
    type: 'vip',
    durationMin: 480,
    priceMin: 560,
    priceMax: 680,
    times: ['09:00', '20:30'],
    platform: 'B-15',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'ตาก', my: 'တာ့ခ်', en: 'Tak' },
    notes: { th: 'แวะพักปั๊มระหว่างทาง 1 ครั้ง', my: 'လမ်းတွင် ဆီဆိုင် ၁ ကြိမ်နား', en: 'One rest stop at a petrol station.' },
  },
  {
    id: 'mc-nan',
    stationId: 'mo-chit',
    destination: { th: 'น่าน', my: 'နန်', en: 'Nan' },
    province: { th: 'น่าน', my: 'နန်', en: 'Nan' },
    company: { th: 'บขส.', my: 'ဘတ်စ်ကုမ္ပဏီ', en: 'The Transport Co.' },
    type: 'first',
    durationMin: 660,
    priceMin: 640,
    priceMax: 760,
    times: ['18:30', '19:45'],
    platform: 'B-19',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'แพร่', my: 'ဖရဲ', en: 'Phrae' },
    notes: { th: 'รถกลางคืนเท่านั้น', my: 'ညကားသာ', en: 'Night bus only.' },
  },
  {
    id: 'st-huahin',
    stationId: 'sai-tai',
    destination: { th: 'หัวหิน', my: 'ဟွာဟင်', en: 'Hua Hin' },
    province: { th: 'ประจวบคีรีขันธ์', my: 'ပရာကျွတ်ခီရီခန်', en: 'Prachuap Khiri Khan' },
    company: { th: 'บขส.', my: 'ဘတ်စ်ကုမ္ပဏီ', en: 'The Transport Co.' },
    type: 'first',
    durationMin: 210,
    priceMin: 180,
    priceMax: 250,
    times: ['06:00', '07:30', '09:00', '11:00', '13:00', '15:00', '17:00', '19:00'],
    platform: '1',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'เพชรบุรี', my: 'ဖက်ချဘူရီ', en: 'Phetchaburi' },
    notes: { th: 'รถบ่อย ลงสถานีหัวหินในเมือง', my: 'မကြာခဏထွက်။ မြို့တွင်း ဟွာဟင်ဂိတ်တွင်ဆင်း', en: 'Frequent. Drops at Hua Hin town terminal.' },
  },
  {
    id: 'st-phuket',
    stationId: 'sai-tai',
    destination: { th: 'ภูเก็ต', my: 'ဖူးခက်', en: 'Phuket' },
    province: { th: 'ภูเก็ต', my: 'ဖူးခက်', en: 'Phuket' },
    company: { th: 'ขนส่งภูเก็ต / สมบัติ', my: 'ဖူးခက်သယ်ယူ / ဆွမ်ဘတ်', en: 'Phuket Bus / Sombat' },
    type: 'vip',
    durationMin: 720,
    priceMin: 780,
    priceMax: 980,
    times: ['18:00', '19:00', '19:45', '20:30'],
    platform: '12',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'ชุมพร สุราษฎร์ พังงา', my: 'ချွန်ဖွန်၊ စူရတ်၊ ဖန်ငါ', en: 'Chumphon, Surat, Phang Nga' },
    notes: { th: 'ถึงสถานีภูเก็ตบขส. เช้ามืด ต่อวินไปป่าตอง', my: 'ဖူးခက်ဘတ်စ်ဂိတ်သို့ မနက်စောရောက်။ ပါတောင်သို့ ဆိုင်ကယ်ဆက်', en: 'Arrives Phuket bus station at dawn. Motorbike to Patong.' },
  },
  {
    id: 'st-krabi',
    stationId: 'sai-tai',
    destination: { th: 'กระบี่', my: 'ခရာဘီ', en: 'Krabi' },
    province: { th: 'กระบี่', my: 'ခရာဘီ', en: 'Krabi' },
    company: { th: 'บขส.', my: 'ဘတ်စ်ကုမ္ပဏီ', en: 'The Transport Co.' },
    type: 'first',
    durationMin: 660,
    priceMin: 650,
    priceMax: 820,
    times: ['18:30', '19:30'],
    platform: '11',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'สุราษฎร์ธานี', my: 'စူရတ်ဌာနီ', en: 'Surat Thani' },
    notes: { th: 'ต่อเรือเกาะพีพีที่ท่าคลองจิหลาด', my: 'ခလောင်ဂျီလတ်ဆိပ်ကမ်းမှ ဖီဖီကျွန်း လှေဆက်', en: 'Phi Phi boats from Khlong Jilad pier.' },
  },
  {
    id: 'st-surat',
    stationId: 'sai-tai',
    destination: { th: 'สุราษฎร์ธานี', my: 'စူရတ်ဌာနီ', en: 'Surat Thani' },
    province: { th: 'สุราษฎร์ธานี', my: 'စူရတ်ဌာနီ', en: 'Surat Thani' },
    company: { th: 'นครชัยแอร์', my: 'နခွန်ချိုင်အဲယား', en: 'Nakhonchai Air' },
    type: 'vip',
    durationMin: 540,
    priceMin: 560,
    priceMax: 720,
    times: ['08:00', '18:00', '20:00'],
    platform: '8',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'ชุมพร', my: 'ချွန်ဖွန်', en: 'Chumphon' },
    notes: { th: 'ต่อเรือสมุย / พะงัน ที่ท่าดอนสัก', my: 'ဒွန်ဆတ်ဆိပ်မှ စမုย / ဖန်ငန် လှေဆက်', en: 'Samui / Phangan boats at Donsak pier.' },
  },
  {
    id: 'st-hatyai',
    stationId: 'sai-tai',
    destination: { th: 'หาดใหญ่', my: 'ဟတ်ယိုင်', en: 'Hat Yai' },
    province: { th: 'สงขลา', my: 'ဆောင်ခလာ', en: 'Songkhla' },
    company: { th: 'บขส.', my: 'ဘတ်စ်ကုမ္ပဏီ', en: 'The Transport Co.' },
    type: 'first',
    durationMin: 780,
    priceMin: 780,
    priceMax: 950,
    times: ['17:30', '18:30', '19:15'],
    platform: '14',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'ชุมพร นครศรี ปัตตานี', my: 'ချွန်ဖွန်၊ နခွန်စီ၊ ပတ္တာနီ', en: 'Chumphon, Nakhon Si, Pattani' },
    notes: { th: 'ต่อด่านสะเดา / ปาดังเบซาร์ ไปมาเลเซีย', my: 'မလေးရှားသို့ စဒေါ / ပါဒန်ဘီဆာ နယ်စပ်ဆက်', en: 'Sadao / Padang Besar borders to Malaysia.' },
  },
  {
    id: 'st-ranong',
    stationId: 'sai-tai',
    destination: { th: 'ระนอง', my: 'ရနောင်း', en: 'Ranong' },
    province: { th: 'ระนอง', my: 'ရနောင်း', en: 'Ranong' },
    company: { th: 'ภาวินีทัวร์', my: 'ဖာဝီနီ', en: 'Pawinee Tour' },
    type: 'first',
    durationMin: 480,
    priceMin: 420,
    priceMax: 540,
    times: ['08:20', '20:00'],
    platform: '18',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'ชุมพร', my: 'ချွန်ဖွန်', en: 'Chumphon' },
    notes: {
      th: 'ต่อเรือข้ามไป Kawthaung (เกาะท่อง) ใช้เวลา 20–45 นาที ด่านเปิด 07:00–16:00 ตามเวลาไทย',
      my: 'ကော့သောင်းသို့ လှေ ၂၀–၄၅ မိနစ်။ ဂိတ်ဖွင့် ထိုင်းစံတော်ချိန် ၀၇:၀၀–၁၆:၀၀',
      en: 'Boat to Kawthaung 20–45 min. Immigration 07:00–16:00 Thai time.',
    },
  },
  {
    id: 'st-kan',
    stationId: 'sai-tai',
    destination: { th: 'กาญจนบุรี', my: 'ကန်ချနဘူရီ', en: 'Kanchanaburi' },
    province: { th: 'กาญจนบุรี', my: 'ကန်ချနဘူရီ', en: 'Kanchanaburi' },
    company: { th: 'บขส.', my: 'ဘတ်စ်ကုမ္ပဏီ', en: 'The Transport Co.' },
    type: 'second',
    durationMin: 150,
    priceMin: 110,
    priceMax: 150,
    times: ['06:00', '08:00', '10:00', '12:00', '14:00', '16:00', '18:00'],
    platform: '17',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'นครปฐม', my: 'နခွန်ပထမ်', en: 'Nakhon Pathom' },
    notes: { th: 'ลงสถานีกาญจนบุรีในเมือง เดินไปสะพานข้ามแม่น้ำแควได้', my: 'မြို့တွင်းဂိတ်တွင်ဆင်း။ ကွေးမြစ်တံတားသို့ လမ်းလျှောက်နိုင်', en: 'Drops in town. Walkable to the River Kwai bridge.' },
  },
  {
    id: 'st-chumphon',
    stationId: 'sai-tai',
    destination: { th: 'ชุมพร', my: 'ချွန်ဖွန်', en: 'Chumphon' },
    province: { th: 'ชุมพร', my: 'ချွန်ဖွန်', en: 'Chumphon' },
    company: { th: 'บขส.', my: 'ဘတ်စ်ကုမ္ပဏီ', en: 'The Transport Co.' },
    type: 'first',
    durationMin: 420,
    priceMin: 380,
    priceMax: 480,
    times: ['08:30', '13:00', '21:00'],
    platform: '6',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'ประจวบ', my: 'ပရာကျွတ်', en: 'Prachuap' },
    notes: { th: 'ต่อเรือเกาะเต่าที่ท่าแพ', my: 'ထာဖဲဆိပ်မှ ကိုးတ่าว လှေဆက်', en: 'Koh Tao boats from Tha Phae pier.' },
  },
  {
    id: 'ek-pattaya',
    stationId: 'ekkamai',
    destination: { th: 'พัทยา', my: 'ပတ္တားယား', en: 'Pattaya' },
    province: { th: 'ชลบุรี', my: 'ချွန်ဘူရီ', en: 'Chonburi' },
    company: { th: 'รถตู้เอกมัย / บขส.', my: 'အက်ကမိုင်ဗန် / ဘတ်စ်', en: 'Ekkamai van / Transport Co.' },
    type: 'express',
    durationMin: 120,
    priceMin: 130,
    priceMax: 180,
    times: ['06:00', '06:30', '07:00', '07:30', '08:00', '08:30', '09:00', '09:30', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00'],
    platform: '3',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'บางนา ศรีราชา', my: 'ဘန်နာ၊ စီရာချာ', en: 'Bang Na, Si Racha' },
    notes: { th: 'รถตู้ทุก 30 นาที ลงพัทยาเหนือ / พัทยากลาง', my: 'ဗန် ၃၀ မိနစ်တစ်ကြိမ်။ မြောက်ပတ္တားယား / အလယ်ပတ္တားယားတွင်ဆင်း', en: 'Vans every 30 min. North / Central Pattaya drop-off.' },
  },
  {
    id: 'ek-rayong',
    stationId: 'ekkamai',
    destination: { th: 'ระยอง', my: 'ရယောင်း', en: 'Rayong' },
    province: { th: 'ระยอง', my: 'ရယောင်း', en: 'Rayong' },
    company: { th: 'บขส.', my: 'ဘတ်စ်ကုမ္ပဏီ', en: 'The Transport Co.' },
    type: 'first',
    durationMin: 180,
    priceMin: 170,
    priceMax: 230,
    times: ['06:30', '08:30', '10:30', '13:00', '15:30', '17:30'],
    platform: '5',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'พัทยา บ้านฉาง', my: 'ပတ္တားယား၊ ဘန်ချန်', en: 'Pattaya, Ban Chang' },
    notes: { th: 'ต่อบ้านเพ ไปเกาะเสม็ด', my: 'ဘန်ဖေးမှ ကိုးစမစ်သို့ ဆက်', en: 'Ban Phe connection to Koh Samet.' },
  },
  {
    id: 'ek-trat',
    stationId: 'ekkamai',
    destination: { th: 'ตราด', my: 'ထရာ့ဒ်', en: 'Trat' },
    province: { th: 'ตราด', my: 'ထရာ့ဒ်', en: 'Trat' },
    company: { th: 'บขส.', my: 'ဘတ်စ်ကုမ္ပဏီ', en: 'The Transport Co.' },
    type: 'first',
    durationMin: 300,
    priceMin: 260,
    priceMax: 340,
    times: ['07:00', '09:00', '12:00', '23:00'],
    platform: '7',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'จันทบุรี', my: 'ချန်သဘူရီ', en: 'Chanthaburi' },
    notes: { th: 'ต่อแหลมงอบไปเกาะช้าง รถตู้หน้าสถานีตราด', my: 'ထရာ့ဒ်ဂိတ်ရှေ့ ဗန်ဖြင့် လမ်ငော့မှ ကိုးချန်သို့', en: 'Laem Ngop vans in front of Trat terminal for Koh Chang.' },
  },
  {
    id: 'ek-chan',
    stationId: 'ekkamai',
    destination: { th: 'จันทบุรี', my: 'ချန်သဘူရီ', en: 'Chanthaburi' },
    province: { th: 'จันทบุรี', my: 'ချန်သဘူရီ', en: 'Chanthaburi' },
    company: { th: 'เชิดชัยทัวร์', my: 'ချာ့ချိုင်', en: 'Cherdchai' },
    type: 'first',
    durationMin: 240,
    priceMin: 210,
    priceMax: 280,
    times: ['07:30', '10:00', '14:00', '18:00'],
    platform: '6',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'ระยอง', my: 'ရယောင်း', en: 'Rayong' },
    notes: { th: 'ตลาดอัญมณีใกล้สถานี', my: 'ဂိတ်အနီး ကျောက်မျက်ဈေး', en: 'Gem market near the station.' },
  },
  {
    id: 'ek-aranya',
    stationId: 'ekkamai',
    destination: { th: 'อรัญประเทศ', my: 'အရန်ယာပရာထေ့ဒ်', en: 'Aranyaprathet' },
    province: { th: 'สระแก้ว', my: 'စရာကဲောင်', en: 'Sa Kaeo' },
    company: { th: 'บขส.', my: 'ဘတ်စ်ကုမ္ပဏီ', en: 'The Transport Co.' },
    type: 'second',
    durationMin: 270,
    priceMin: 200,
    priceMax: 260,
    times: ['06:00', '09:00', '12:00'],
    platform: '8',
    days: { th: 'ทุกวัน', my: 'နေ့စဉ်', en: 'Daily' },
    via: { th: 'ฉะเชิงเทรา สระแก้ว', my: 'ချာချိုန်ဆောင်၊ စရာကဲောင်', en: 'Chachoengsao, Sa Kaeo' },
    notes: { th: 'ด่านปอยเปต (กัมพูชา) เดินต่อจากสถานี 10 นาที', my: 'ပွိုင်ပက် (ကမ္ဘောဒီးယား) နယ်စပ်သည် ဂိတ်မှ ၁၀ မိနစ်လမ်းလျှောက်', en: 'Poipet (Cambodia) border is a 10-min walk from the station.' },
  },
];

export const guides: Guide[] = [
  {
    id: 'first-time',
    icon: 'compass',
    color: '#C4491D',
    title: { th: 'มาสถานีครั้งแรก', my: 'ဂိတ်သို့ ပထမဆုံးအကြိမ်', en: 'First time at a terminal' },
    subtitle: { th: 'ซื้อตั๋ว หาชานชาลา และขึ้นรถให้ทัน', my: 'လက်မှတ်ဝယ်၊ ပလက်ဖောင်းရှာ၊ ကားမမှီအောင်တက်ပါ', en: 'Buy a ticket, find the platform, board on time' },
    minutes: 4,
    sections: [
      {
        heading: { th: '1. เลือกสถานีให้ถูก', my: '၁. ဂိတ်မှန်ကိုရွေးပါ', en: '1. Pick the right terminal' },
        body: {
          th: 'เหนือ/อีสาน = หมอชิต 2 · ใต้/ตะวันตก = สายใต้ใหม่ · ตะวันออก (พัทยา ระยอง ตราด) = เอกมัย อย่าไปหมอชิตเก่าหรือสายใต้เก่า',
          my: 'မြောက်/အီစန် = မော်ချစ် ၂ · တောင်/အနောက် = ဆိုင်တိုင်းအသစ် · အရှေ့ (ပတ္တားယား၊ ရယောင်း၊ ထရာ့ဒ်) = အက်ကမိုင်။ မော်ချစ်အဟောင်း သို့မဟုတ် ဆိုင်တိုင်းအဟောင်း မသွားပါနှင့်',
          en: 'North/Isaan = Mo Chit 2 · South/West = Sai Tai Mai · East (Pattaya, Rayong, Trat) = Ekkamai. Avoid old Mo Chit or old Southern terminal.',
        },
      },
      {
        heading: { th: '2. ซื้อตั๋ว', my: '၂. လက်မှတ်ဝယ်ပါ', en: '2. Buy a ticket' },
        body: {
          th: 'เคาน์เตอร์บริษัทมีป้ายปลายทางภาษาไทย ชำระเงินสดหรือพร้อมเพย์ เก็บตั๋วไว้ให้พนักงานตรวจก่อนขึ้น อย่าซื้อจากนายหน้าหน้าสถานีในราคาสูง',
          my: 'ကုမ္ပဏီကောင်တာတွင် ထိုင်းလိုဦးတည်ရာဆိုင်းဘုတ်ရှိသည်။ ငွေသား သို့မဟုတ် PromptPay။ ကားမတက်မီ လက်မှတ်ပြပါ။ ဂိတ်ရှေ့ ပွဲစားထံမှ ဈေးကြီးမဝယ်ပါနှင့်',
          en: 'Company counters show Thai destination signs. Cash or PromptPay. Keep the ticket for boarding check. Avoid touts outside.',
        },
      },
      {
        heading: { th: '3. หาชานชาลา', my: '၃. ပလက်ဖောင်းရှာပါ', en: '3. Find the platform' },
        body: {
          th: 'ตัวเลขชานชาลาอยู่บนตั๋ว (เช่น B-16) ดูผังในแอปหรือป้ายจอกลางโถง ไปรอที่ประตูขึ้นรถก่อนเวลา 15 นาที',
          my: 'ပလက်ဖောင်းနံပါတ် လက်မှတ်ပေါ်တွင်ရှိသည် (ဥပမာ B-16)။ အက်ပ်မြေပုံ သို့မဟုတ် ခန်းမမျက်နှာပြင်ကိုကြည့်ပါ။ ၁၅ မိနစ်ကြို၍ စောင့်ပါ',
          en: 'Platform number is on the ticket (e.g. B-16). Use the in-app map or hall screens. Wait at the gate 15 minutes early.',
        },
      },
    ],
  },
  {
    id: 'myanmar',
    icon: 'flag',
    color: '#1B5E56',
    title: { th: 'จากเมียนมาเข้ากรุงเทพฯ', my: 'မြန်မာပြည်မှ ဘန်ကောက်သို့', en: 'From Myanmar into Bangkok' },
    subtitle: { th: 'แม่สอด–เมียวดี และระนอง–Kawthaung', my: 'မဲဆောက်–မြဝတီ နှင့် ရနောင်း–ကော့သောင်း', en: 'Mae Sot–Myawaddy and Ranong–Kawthaung' },
    minutes: 6,
    sections: [
      {
        heading: { th: 'เส้นทางแม่สอด (ยอดนิยม)', my: 'မဲဆောက်လမ်းကြောင်း (လူအသုံးများဆုံး)', en: 'Mae Sot route (most used)' },
        body: {
          th: 'เมียวดี → ด่านไทย (เปิด 05:30–20:00) → วิน/สองแถว 15–25 นาทีเข้าตัวเมืองแม่สอด → รถทัวร์หมอชิต 2 ใช้เวลา 8–9 ชม. ราคา 420–560 บาท ออกเช้าและค่ำ',
          my: 'မြဝတီ → ထိုင်းဂိတ် (၀၅:၃၀–၂၀:၀၀) → ဆိုင်ကယ်/ဆွန် grav ၁၅–၂၅ မိနစ် မဲဆောက်မြို့ → မော်ချစ် ၂ သို့ ခရီးသည်ကား ၈–၉ နာရီ၊ ၄၂၀–၅၆၀ ဘတ်၊ နံနက်နှင့်ညထွက်',
          en: 'Myawaddy → Thai gate (05:30–20:00) → 15–25 min into Mae Sot town → coach to Mo Chit 2 in 8–9 hrs, 420–560 THB, morning and night.',
        },
      },
      {
        heading: { th: 'เส้นทางระนอง / Kawthaung', my: 'ရနောင်း / ကော့သောင်း လမ်းကြောင်း', en: 'Ranong / Kawthaung route' },
        body: {
          th: 'เรือข้ามฝาก 20–45 นาที ด่านไทยเปิด 07:00–16:00 จากนั้นรถทัวร์สายใต้ใหม่ 8 ชม. เข้ากรุงเทพฯ',
          my: 'လှေ ၂၀–၄၅ မိနစ်။ ထိုင်းဂိတ် ၀၇:၀၀–၁၆:၀၀။ ထို့နောက် ဆိုင်တိုင်းအသစ်သို့ ၈ နာရီ',
          en: 'Ferry 20–45 min. Thai immigration 07:00–16:00. Then 8 hrs to Sai Tai Mai.',
        },
      },
      {
        heading: { th: 'เอกสารและซิม', my: 'စာရွက်စာတမ်းနှင့် SIM', en: 'Papers and SIM' },
        body: {
          th: 'พาสปอร์ตและบัตรผ่านแดนตามประเภทวีซ่า แลกเงินบาทที่ด่านหรือในเมือง ซื้อซิม AIS/DTAC ที่ 7-Eleven แสดงพาสปอร์ต',
          my: 'ပတ်စ်ပို့နှင့် ဗီဇာအမျိုးအစားအလိုက် နယ်စပ်ကတ်။ ဂိတ် သို့မဟုတ် မြို့တွင် ဘတ်လဲပါ။ 7-Eleven တွင် AIS/DTAC SIM ဝယ်ရန် ပတ်စ်ပို့ပြပါ',
          en: 'Passport and the correct border pass/visa. Change to THB at the gate or in town. Buy AIS/DTAC SIM at 7-Eleven with your passport.',
        },
      },
      {
        heading: { th: 'ภาษาที่เคาน์เตอร์', my: 'ကောင်တာတွင် ဘာသာစကား', en: 'Language at the counter' },
        body: {
          th: 'พนักงานส่วนใหญ่พูดไทย บางคนเข้าใจอังกฤษเล็กน้อย ที่หมอชิตมักมีคนพม่าช่วยแปล ใช้แอปนี้โชว์ปลายทางภาษาไทยได้',
          my: 'ဝန်ထမ်းအများစု ထိုင်းလိုပြောသည်။ အချို့ အင်္ဂလိပ်နည်းနည်းနားလည်သည်။ မော်ချစ်တွင် မြန်မာဘာသာပြန်ကူညီသူရှိတတ်သည်။ ဤအက်ပ်တွင် ထိုင်းလိုဦးတည်ရာကို ပြနိုင်သည်',
          en: 'Most staff speak Thai, some basic English. At Mo Chit, Myanmar speakers often help. Show the Thai destination name from this app.',
        },
      },
    ],
  },
  {
    id: 'tickets',
    icon: 'ticket',
    color: '#C9A227',
    title: { th: 'ซื้อตั๋วและชั้นรถ', my: 'လက်မှတ်နှင့် ကားအဆင့်', en: 'Tickets and bus classes' },
    subtitle: { th: 'VIP ชั้น 1 ชั้น 2 ต่างกันอย่างไร', my: 'VIP၊ ပထမတန်း၊ ဒုတိယတန်း ကွာခြားပုံ', en: 'VIP vs 1st vs 2nd class' },
    minutes: 3,
    sections: [
      {
        heading: { th: 'VIP', my: 'VIP', en: 'VIP' },
        body: {
          th: 'ที่นั่ง 24–32 ปรับเอนลึก มีผ้าห่ม น้ำ อาหารกล่อง เหมาะกับเชียงใหม่ ภูเก็ต ขอนแก่น ราคาสูงกว่า 150–250 บาท',
          my: 'ခုံ ၂၄–၃၂၊ လှဲအိပ်နိုင်၊ စောင်၊ ရေ၊ ထမင်းဘူး။ ချင်းမိုင်၊ ဖူးခက်၊ ခွန်ကဲန်အတွက်သင့်တော်။ ၁၅၀–၂၅၀ ဘတ် ပိုကြေး',
          en: '24–32 deep-recline seats, blanket, water, meal box. Best for Chiang Mai, Phuket, Khon Kaen. 150–250 THB extra.',
        },
      },
      {
        heading: { th: 'ชั้น 1', my: 'ပထမတန်း', en: '1st class' },
        body: {
          th: 'แอร์ 2+2 ที่นั่งกว้างปานกลาง มีจุดพัก 1–2 ครั้ง คุ้มค่าที่สุดสำหรับแม่สอดและหัวหิน',
          my: 'အဲယား ၂+၂၊ ခုံအလယ်အလတ်ကျယ်၊ ၁–၂ ကြိမ်နား။ မဲဆောက်နှင့် ဟွာဟင်အတွက် အတန်ဆုံး',
          en: 'A/C 2+2, medium seats, 1–2 rest stops. Best value for Mae Sot and Hua Hin.',
        },
      },
      {
        heading: { th: 'ชั้น 2 / รถตู้', my: 'ဒုတိယတန်း / ဗန်', en: '2nd class / van' },
        body: {
          th: 'ถูกกว่า ที่นั่งแคบ รถตู้พัทยาออกบ่อยแต่ที่เก็บกระเป๋าจำกัด',
          my: 'ပိုသက်သာ၊ ခုံကျဉ်း။ ပတ္တားယားဗန် မကြာခဏထွက်သော်လည်း အိတ်နေရာနည်း',
          en: 'Cheaper, tighter seats. Pattaya vans are frequent but luggage space is limited.',
        },
      },
    ],
  },
  {
    id: 'airports',
    icon: 'airplane',
    color: '#2B4C7E',
    title: { th: 'จากสนามบินสู่สถานี', my: 'လေဆိပ်မှ ဘတ်စ်ဂိတ်သို့', en: 'Airport to terminal' },
    subtitle: { th: 'สุวรรณภูมิและดอนเมือง', my: 'သုဝဏ္ဏဘူမိနှင့် ဒွန်မောင်း', en: 'Suvarnabhumi and Don Mueang' },
    minutes: 4,
    sections: [
      {
        heading: { th: 'สุวรรณภูมิ (BKK)', my: 'သုဝဏ္ဏဘူမိ (BKK)', en: 'Suvarnabhumi (BKK)' },
        body: {
          th: 'ไปเอกมัย: Airport Rail Link → พระโขนง → BTS 1 สถานี รวม 45–60 นาที · ไปหมอชิต: Airport Rail Link ถึงพญาไท ต่อ BTS ถึงหมอชิต แล้ววิน 10 นาที · ไปสายใต้ใหม่: เข้าเมืองแล้ว Grab 90–130 นาที',
          my: 'အက်ကမိုင်: Airport Rail Link → ဖရာခနောင် → BTS ၁ ဘူတာ၊ ၄၅–၆၀ မိနစ် · မော်ချစ်: ပယာထိုင်းအထိ ရထား၊ BTS မော်ချစ်၊ ဆိုင်ကယ် ၁၀ မိနစ် · ဆိုင်တိုင်းအသစ်: မြို့တွင်းဝင်ပြီး Grab ၉၀–၁၃၀ မိနစ်',
          en: 'Ekkamai: Airport Rail Link → Phra Khanong → 1 BTS stop, 45–60 min · Mo Chit: rail to Phaya Thai, BTS to Mo Chit, 10 min motorbike · Sai Tai Mai: into town then Grab 90–130 min.',
        },
      },
      {
        heading: { th: 'ดอนเมือง (DMK)', my: 'ဒွန်မောင်း (DMK)', en: 'Don Mueang (DMK)' },
        body: {
          th: 'ใกล้หมอชิตที่สุด แท็กซี่ 25–40 นาที หรือรถ A1 ไปอนุสาวรีย์แล้วต่อ BTS ไม่แนะนำดอนเมืองถ้าจะไปสายใต้ใหม่ตอนดึก',
          my: 'မော်ချစ်နှင့် အနီးဆုံး။ တက္ကစီ ၂၅–၄၀ မိနစ် သို့မဟုတ် A1 ဖြင့် အထိမ်းအမှတ်သို့။ ညနှောင်းပိုင်း ဆိုင်တိုင်းအသစ်သို့ ဒွန်မောင်းမှ မသွားရန်',
          en: 'Closest to Mo Chit. Taxi 25–40 min or A1 to the monument then BTS. Avoid Don Mueang late at night if you need Sai Tai Mai.',
        },
      },
    ],
  },
  {
    id: 'safety',
    icon: 'shield-checkmark',
    color: '#8E2F12',
    title: { th: 'ความปลอดภัยและมารยาท', my: 'လုံခြုံရေးနှင့် စည်းကမ်း', en: 'Safety and etiquette' },
    subtitle: { th: 'ของมีค่า จุดขึ้นรถ และสิ่งที่ควรรู้', my: 'တန်ဖိုးရှိပစ္စည်း၊ ကားတက်ရာနှင့် သိထားသင့်သည်များ', en: 'Valuables, boarding, and what to know' },
    minutes: 3,
    sections: [
      {
        heading: { th: 'ของมีค่า', my: 'တန်ဖိုးရှိပစ္စည်း', en: 'Valuables' },
        body: {
          th: 'พาสปอร์ต เงิน โทรศัพท์อยู่ในกระเป๋าที่อุ้มตลอด กระเป๋าใบใหญ่ขึ้นช่องใต้ท้องรถ มีแท็กสีคู่กับตั๋ว',
          my: 'ပတ်စ်ပို့၊ ငွေ၊ ဖုန်းကို လက်ကိုင်အိတ်တွင် အမြဲထားပါ။ အိတ်ကြီးများကို ကားအောက်ခန်းတွင် တင်သည်။ လက်မှတ်နှင့် အရောင်တူ တက်ဂ်ရှိသည်',
          en: 'Keep passport, cash and phone in a bag you hold. Large bags go in the undercarriage with a colour tag matching your ticket.',
        },
      },
      {
        heading: { th: 'ฉุกเฉิน', my: 'အရေးပေါ်', en: 'Emergency' },
        body: {
          th: 'ตำรวจท่องเที่ยว 1155 · แพทย์ฉุกเฉิน 1669 · แจ้งเหตุด่วน 191 มีจุดประชาสัมพันธ์ชั้น 1 ทุกสถานี',
          my: 'ခရီးသွားရဲ ၁၁၅၅ · ဆေးအရေးပေါ် ၁၆၆၉ · အရေးပေါ် ၁၉၁။ ဂိတ်တိုင်း ပထမထပ်တွင် အချက်အလက်စားပွဲရှိသည်',
          en: 'Tourist police 1155 · Medical 1669 · Emergency 191. Info desks on 1F at every terminal.',
        },
      },
      {
        heading: { th: 'บนรถ', my: 'ကားပေါ်တွင်', en: 'On the bus' },
        body: {
          th: 'ห้ามสูบ เสียงโทรศัพท์เบา รองเท้าถอดได้บนรถ VIP บางคัน แวะปั๊มให้เข้าห้องน้ำตามพนักงาน',
          my: 'ဆေးလိပ်မသောက်ရ။ ဖုန်းအသံတိတ်။ VIP အချို့တွင် ဖိနပ်ချွတ်နိုင်။ ဆီဆိုင်နားချိန်တွင် အိမ်သာသုံးရန် ဝန်ထမ်းလိုက်ပါ',
          en: 'No smoking, keep calls quiet. Shoes may come off on some VIP coaches. Use rest-stop toilets when staff announce.',
        },
      },
    ],
  },
  {
    id: 'roads',
    icon: 'map',
    color: '#1B5E56',
    title: { th: 'ขับรถเข้าสถานี', my: 'ကားနှင့်ဂိတ်သို့ဝင်ရန်', en: 'Driving into the terminals' },
    subtitle: { th: 'ทางด่วน ทางเข้า และที่จอด', my: 'အမြန်လမ်း၊ ဝင်ပေါက်နှင့် ရပ်နားရန်', en: 'Expressways, entries and parking' },
    minutes: 3,
    sections: [
      {
        heading: { th: 'หมอชิต 2', my: 'မော်ချစ် ၂', en: 'Mo Chit 2' },
        body: {
          th: 'ใช้ทางด่วนงามวงศ์วานหรือวิภาวดี ลงจตุจักร เข้าถ.กำแพงเพชร 2 ที่จอดด้านข้างอาคาร ชั่วโมงละ 20–30 บาท เต็มช่วงเช้าวันหยุด',
          my: 'ငမ်ဝေါင်ဝမ် သို့မဟုတ် ဝီဖာဝဒီ အမြန်လမ်း၊ ချာတူချက်မှဆင်း၊ ကမ်ဖန်ဖက် ၂ သို့။ အဆောက်အအုံဘေး ရပ်နား နာရီ ၂၀–၃၀ ဘတ်။ ပိတ်ရက်နံနက်တွင် ပြည့်တတ်',
          en: 'Ngarm Wongwan or Vibhavadi expressway, Chatuchak exit, Kamphaeng Phet 2. Side-building parking 20–30 THB/hr. Full on holiday mornings.',
        },
      },
      {
        heading: { th: 'สายใต้ใหม่', my: 'ဆိုင်တိုင်းအသစ်', en: 'Sai Tai Mai' },
        body: {
          th: 'ถ.บรมราชชนนีรถติด 16:00–19:30 เข้าอาคารจอดด้านทิศใต้ ตามป้าย บขส.',
          my: 'ဘိုရမ်ရာ့ချာနီလမ်း ၁၆:၀၀–၁၉:၃၀ ပိတ်သည်။ တောင်ဘက်ရပ်နားအဆောက်အအုံ။ ဘတ်စ်ဂိတ်ဆိုင်းဘုတ်လိုက်ပါ',
          en: 'Borommaratchachonnani jams 16:00–19:30. South parking garage. Follow บขส. signs.',
        },
      },
      {
        heading: { th: 'เอกมัย', my: 'အက်ကမိုင်', en: 'Ekkamai' },
        body: {
          th: 'ที่จอดน้อยมาก แนะนำ BTS เอกมัย ถ้าขับรถใช้ซอยสุขุมวิท 40 ฝั่งขาออก',
          my: 'ရပ်နားရန် အလွန်နည်းသည်။ BTS အက်ကမိုင်ကို အကြံပြုသည်။ ကားမောင်းလျှင် သုခွမ်ဝစ် ဆွိုင် ၄၀ မြို့အထွက်ဘက်',
          en: 'Very little parking. Take BTS Ekkamai. Drivers use Soi Sukhumvit 40 outbound.',
        },
      },
    ],
  },
];

export const maps: StationMap[] = [
  {
    id: 'city',
    stationId: 'all',
    kind: 'city',
    title: { th: 'แผนที่รวมสถานีกรุงเทพฯ', my: 'ဘန်ကောက်ဂိတ်များ မြေပုံ', en: 'Bangkok terminals overview' },
    subtitle: { th: 'หมอชิต สายใต้ใหม่ เอกมัย และสนามบิน', my: 'မော်ချစ်၊ ဆိုင်တိုင်းအသစ်၊ အက်ကမိုင်နှင့် လေဆိပ်များ', en: 'Mo Chit, Sai Tai Mai, Ekkamai and airports' },
    updated: '2026-03-12',
    legend: [
      { color: '#C4491D', label: { th: 'หมอชิต 2 (เหนือ/อีสาน)', my: 'မော်ချစ် ၂ (မြောက်/အီစန်)', en: 'Mo Chit 2 (N/NE)' } },
      { color: '#1B5E56', label: { th: 'สายใต้ใหม่ (ใต้/ตะวันตก)', my: 'ဆိုင်တိုင်းအသစ် (တောင်/အနောက်)', en: 'Sai Tai Mai (S/W)' } },
      { color: '#2B4C7E', label: { th: 'เอกมัย (ตะวันออก)', my: 'အက်ကမိုင် (အရှေ့)', en: 'Ekkamai (East)' } },
      { color: '#9EC9C4', label: { th: 'แม่น้ำเจ้าพระยา', my: 'ချောင်းဖရာယာမြစ်', en: 'Chao Phraya river' } },
    ],
  },
  {
    id: 'mo-chit-term',
    stationId: 'mo-chit',
    kind: 'terminal',
    title: { th: 'ผังอาคารหมอชิต 2', my: 'မော်ချစ် ၂ အဆောက်အအုံပုံစံ', en: 'Mo Chit 2 terminal layout' },
    subtitle: { th: 'ชั้น 1 ตั๋วและชานชาลา · ชั้น 2 อาหาร', my: 'ပထမထပ် လက်မှတ်နှင့် ပလက်ဖောင်း · ဒုတိယထပ် အစားအသောက်', en: '1F tickets & platforms · 2F food' },
    updated: '2026-03-12',
    legend: [
      { color: '#C4491D', label: { th: 'ชานชาลาขึ้นรถ', my: 'ကားတက်ရာ', en: 'Boarding' } },
      { color: '#C9A227', label: { th: 'เคาน์เตอร์ตั๋ว', my: 'လက်မှတ်ကောင်တာ', en: 'Tickets' } },
      { color: '#1B5E56', label: { th: 'ห้องรอ / อาหาร', my: 'စောင့်ခန်း / စားသောက်', en: 'Waiting / food' } },
    ],
  },
  {
    id: 'mo-chit-road',
    stationId: 'mo-chit',
    kind: 'road',
    title: { th: 'ถนนเข้าหมอชิต 2', my: 'မော်ချစ် ၂ ဝင်လမ်းများ', en: 'Roads into Mo Chit 2' },
    subtitle: { th: 'กำแพงเพชร 2 · พหลโยธิน · งามวงศ์วาน', my: 'ကမ်ဖန်ဖက် ၂ · ဖဟိုယိုသင် · ငမ်ဝေါင်ဝမ်', en: 'Kamphaeng Phet 2 · Phahonyothin · Ngarm Wongwan' },
    updated: '2026-03-12',
    legend: [
      { color: '#C4491D', label: { th: 'ทางเข้าหลัก', my: 'အဓိကဝင်ပေါက်', en: 'Main entrance' } },
      { color: '#2B4C7E', label: { th: 'ทางด่วน', my: 'အမြန်လမ်း', en: 'Expressway' } },
      { color: '#1B5E56', label: { th: 'BTS / MRT', my: 'BTS / MRT', en: 'BTS / MRT' } },
    ],
  },
  {
    id: 'sai-tai-term',
    stationId: 'sai-tai',
    kind: 'terminal',
    title: { th: 'ผังอาคารสายใต้ใหม่', my: 'ဆိုင်တိုင်းအသစ် အဆောက်အအုံပုံစံ', en: 'Sai Tai Mai terminal layout' },
    subtitle: { th: 'ชานชาลาใต้ 1–16 · ตะวันตก 17–20', my: 'တောင်ပလက်ဖောင်း ၁–၁၆ · အနောက် ၁၇–၂၀', en: 'South platforms 1–16 · West 17–20' },
    updated: '2026-03-10',
    legend: [
      { color: '#1B5E56', label: { th: 'ชานชาลาภาคใต้', my: 'တောင်ပလက်ဖောင်း', en: 'South platforms' } },
      { color: '#C4491D', label: { th: 'ชานชาลาตะวันตก', my: 'အနောက်ပလက်ဖောင်း', en: 'West platforms' } },
      { color: '#C9A227', label: { th: 'ตั๋ว', my: 'လက်မှတ်', en: 'Tickets' } },
    ],
  },
  {
    id: 'sai-tai-road',
    stationId: 'sai-tai',
    kind: 'road',
    title: { th: 'ถนนเข้าสายใต้ใหม่', my: 'ဆိုင်တိုင်းအသစ် ဝင်လမ်းများ', en: 'Roads into Sai Tai Mai' },
    subtitle: { th: 'บรมราชชนนี · ราชพฤกษ์ · พุทธมณฑล', my: 'ဘိုရမ်ရာ့ချာနီ · ရာ့ချာဖရိုက် · ဖုတ္ဓမဏ္ဍိုင်', en: 'Borommaratchachonnani · Ratchaphruek · Phutthamonthon' },
    updated: '2026-03-10',
    legend: [
      { color: '#1B5E56', label: { th: 'ทางเข้าหลัก', my: 'အဓိကဝင်ပေါက်', en: 'Main entrance' } },
      { color: '#C4491D', label: { th: 'จุดรถติดเย็น', my: 'ညနေယာဉ်ကြောပိတ်ရာ', en: 'Evening jam zone' } },
    ],
  },
  {
    id: 'ekkamai-term',
    stationId: 'ekkamai',
    kind: 'terminal',
    title: { th: 'ผังอาคารเอกมัย', my: 'အက်ကမိုင် အဆောက်အအုံပုံစံ', en: 'Ekkamai terminal layout' },
    subtitle: { th: 'อาคารเดียว เชื่อม BTS เอกมัย', my: 'အဆောက်အအုံတစ်ခုတည်း၊ BTS အက်ကမိုင်နှင့် ချိတ်', en: 'Single hall linked to BTS Ekkamai' },
    updated: '2026-03-08',
    legend: [
      { color: '#2B4C7E', label: { th: 'ชานชาลา', my: 'ပလက်ဖောင်း', en: 'Platforms' } },
      { color: '#C9A227', label: { th: 'ตั๋ว', my: 'လက်မှတ်', en: 'Tickets' } },
      { color: '#1B5E56', label: { th: 'สะพาน BTS', my: 'BTS တံတား', en: 'BTS skywalk' } },
    ],
  },
  {
    id: 'airport-links',
    stationId: 'all',
    kind: 'airport',
    title: { th: 'แผนที่เชื่อมสนามบิน', my: 'လေဆိပ်ချိတ်ဆက်မြေပုံ', en: 'Airport connection map' },
    subtitle: { th: 'BKK · DMK สู่สามสถานีขนส่ง', my: 'BKK · DMK မှ ဂိတ်သုံးခုသို့', en: 'BKK · DMK to the three terminals' },
    updated: '2026-03-12',
    legend: [
      { color: '#C9A227', label: { th: 'Airport Rail Link', my: 'လေဆိပ်ရထား', en: 'Airport Rail Link' } },
      { color: '#1B5E56', label: { th: 'BTS สายสุขุมวิท', my: 'BTS သုခွမ်ဝစ်လိုင်း', en: 'BTS Sukhumvit' } },
      { color: '#C4491D', label: { th: 'แท็กซี่ / รถ A1', my: 'တက္ကစီ / A1 ကား', en: 'Taxi / A1 bus' } },
    ],
  },
];

export function stationById(id: string) {
  return stations.find((s) => s.id === id);
}

export function routesByStation(id: string) {
  return routes.filter((r) => r.stationId === id);
}

export function formatDuration(min: number, lang: 'th' | 'my' | 'en') {
  const h = Math.floor(min / 60);
  const m = min % 60;
  if (lang === 'th') return m ? `${h} ชม. ${m} นาที` : `${h} ชม.`;
  if (lang === 'my') return m ? `${h} နာရီ ${m} မိနစ်` : `${h} နာရီ`;
  return m ? `${h}h ${m}m` : `${h}h`;
}

export function minsUntil(hhmm: string, now = new Date()) {
  const [h, m] = hhmm.split(':').map(Number);
  const target = new Date(now);
  target.setHours(h, m, 0, 0);
  let diff = (target.getTime() - now.getTime()) / 60000;
  if (diff < -5) diff += 24 * 60;
  return Math.round(diff);
}

export const popularAiQuestions = {
  th: [
    'ไปแม่สอดยังไง?',
    'หมอชิต 2 อยู่ที่ไหน?',
    'ตารางรถเชียงใหม่',
    'จากสุวรรณภูมิไปเอกมัย',
    'ด่านเมียวดีเปิดกี่โมง?',
  ],
  my: [
    'မဲဆောက် ဘယ်လိုသွားမလဲ?',
    'မော်ချစ် ၂ ဘယ်မှာလဲ?',
    'ချင်းမိုင် ကားအချိန်ဇယား',
    'သုဝဏ္ဏဘူမိမှ အက်ကမိုင်',
    'မြဝတီဂိတ် ဘယ်အချိန်ဖွင့်လဲ?',
  ],
  en: [
    'How do I go to Mae Sot?',
    'Where is Mo Chit 2?',
    'Chiang Mai timetable',
    'BKK airport to Ekkamai',
    'What time does Myawaddy gate open?',
  ],
};
